modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="reauth"
version="${file.jarVersion}"
displayName="ReAuth"
updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/reauth"
authors="TechnicianLP"
description="A Mod to renew your Session"

[[dependencies.reauth]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.16)"
    ordering="NONE"
    side="CLIENT"
